[package]
name = "cisco-logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syslog_loose = "0.16.0"
paris = "1.5.8"
rust-ini = "0.10.3"
